---
title: "Testing the Two Functions"
author: "Group 10"
format: html
editor: visual
---

```{r}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load the data

```{r}
devtools::install_github("Data-Science-I/lab2-group10_01/packageg10")
library(packageg10)
packageg10::create_boxplot
packageg10::calculate_drg_statistics

library(ggplot2)
library(dplyr)
library(devtools)
library(roxygen2)
```


```{r}
library(readr)
library(here)
load("../packageg10/data/DRG_data.RData")
#devtools::install_github("Data-Science-I/lab2-group10_01/packageg10")
#data <- read_csv(here("data/DRG_data.csv"))
```

Funtion 1:

```{r}
#source("../packageg10/R/function1g10.R")
#devtools::install("../packageg10")
create_boxplot(data, "Average.Medicare.Payments")  # Boxplot for Medicare Payments
create_boxplot(data, "Average.Total.Payments")     # Boxplot for Total Payments
create_boxplot(data, "Average.Covered.Charges") # Boxplot for Covered Charges
```

Function 2

```{r}
#change the path as needed 
#source("../packageg10/R/function2g10.R")
#devtools::install("../packageg10")
#library(packageg10)
```

```{r}
library(dplyr)
# Calculate and print the mean for each DRG Definition
result_mean <- calculate_drg_statistics(data, "mean")
print(result_mean)  # Displays the mean of Average Medicare Payments by DRG Definition

# Calculate and print the median for each DRG Definition
result_median <- calculate_drg_statistics(data, "median")
print(result_median)  # Displays the median of Average Medicare Payments by DRG Definition

# Calculate and print the standard deviation for each DRG Definition
result_sd <- calculate_drg_statistics(data, "sd")
print(result_sd)  # Displays the standard deviation of Average Medicare Payments by DRG Definition
```
